# 📜 09 Error Handling
[panic!](#1-unrecoverable-errors-with-panic)&emsp;[Result](#2-recoverable-errors-with-result)&emsp;[panic!⭕❌](#3-to-panic-or-not-to-panic)
<br><br>

## 1. Unrecoverable Errors with panic!🤯

### ```panic!```
* 패닉이 발생하면 프로그램은 많은 일을 함 (실패 메시지 출력 → 스택 되감고 청소하기 → 종료)
* 아래 설정을 통해 *그만두기*를 설정하여 ```build``` 시에 되감기가 아닌 그만두기로 설정할 수 있음
  <br>

  ```rust
  // Cargo.toml 파일 추가 내용
  [profil.release]
  panic = 'abort'
  ```
  <img src="https://github.com/redzzzi/Rust23summer/assets/127263392/5c225a1f-1bde-47c1-ac6b-2234bd8a5c30" width="700px"><br>
    * panic! 발생한 부분에 대한 설명이 있음
---
### panic! 백트레이스 사용
* *backtrace*: 어떤 지점에 도달하기까지 호출해온 모든 함수의 리스트
* ```RUST_BACKTRACE=1 cargo run``` 명령어를 통해 문제를 일으킨 지점을 순서대로 찾아갈 수 있음
<br>

## 2. Recoverable Errors with Result
💡 [2장] ```Result``` 열거형은 ```Ok```와 ```Err``` 두 variant를 갖는다💡

### ```File::open``` 함수
* 반환 타임: ```Result<T, E>```
* 파일 열기 코드
  <br>

  ```rust
  use std::fs::File;

  fn main() {
      let f = File::open("hello.txt");
  }
  ```
* ```match``` 표현식을 이용하여 ```Result``` 처리하기
  <br>

  ```rust
  use std::fs::File;

  fn main() {
      let f = File::open("hello.txt");
  
      let f = match f {
          Ok(file) => file,  // File::open이 성공하여 Ok 인스턴스 전
          Err(error) => {
              panic!("There was a problem opening the file: {:?}", error)
          },
      };
  }
  ```
  ```rust
  // hello.txt 파일 존재하지 않음
  thread 'main' panicked at 'There was a problem opening the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:9:13
  ```
<br>

### 서로 다른 에러에 대해 매칭
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");  // 파일 열기 시도, 결과 리턴

    let f = match f {
        Ok(file) => file,  // 성공적으로 파일이 열릴 시 file 리턴
        Err(ref error) if error.kind() == ErrorKind::NotFound => {  // ErrorKind::NotFound variant 사용됨
            match File::create("hello.txt") {  // 파일이 존재하지 않는 경우 hello.txt 파일 생성
                Ok(fc) => fc,  // 파일 성공적으로 생성 시 fc 반환
                Err(e) => {  // 오류 발생 시 패닉 매크로와 함께 종료됨
                    panic!(
                        "Tried to create file but there was a problem: {:?}",
                        e
                    )
                },
            }
        },
        Err(error) => {  // 파일 열 때 오류 발생 시 패닉 매크로와 함께 종료
            panic!(
                "There was a problem opening the file: {:?}",
                error
            )
        },
    };
}
```
* ```io::Error```
    * 표준 라이브러리에서 제공하는 구조체
    * ```kind``` 메소드를 호출하여 ```io::ErrorKind``` 값을 얻음
    * ```io::ErrorKind```: ```io``` 연산으로부터 발생할 수 있는 여러 종류의 에러를 표현하는 variant를 가진 열거형
* *match guard*: 조건문 ```if error.kind() == ErrorKind::NotFound```
    * 추가 조건문 역할
    * ```match``` 패턴에서 ```ref```을 사용하여 ```error```의 소유권이 가드 조건문으로 이동되지 않고 참조만 되도록 함!!
    * ```ref```는 값을 매치하여 그 참조자를 제공함 (```&```는 참조자를 매치하고 그 값 제공)
<br>

### ```unwrap```과 ```expect```
match 구문과 비슷한 역할을 하는 ```unwrap``` 메소드
* ```Result``` 값으로 ```Ok``` 또는 ```Err```을 리턴
<br>

```rust
let f = File::open("hello.txt").unwrap();
```
<br><br>

```expect``` 메소드
* 에러 메시지의 내용을 설정할 수 있어, 패닉 메시지를 파악하기 쉬워짐
* unwrap에는 문자열이 안 들어감
<br>

```rust
let f = File::open("hello.txt").expect("Failed to open hello.txt");
```
  
<br>

## 3. To panic!🤯 or Not to panic!🤓
┌ ```panic!``` 사용 → 코드가 복구 불가함을 인정하는 것<br>
│<Br>
└ ```Result``` 사용 → 바로 코드의 복구 가능성을 따지기보다는, 옵션을 제공하는 것
<br>
